version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQAMJAN30MayProject
  gitServerName: SIQAMJAN
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: SIQACloudStreamsTests
  version: "1.0"
  gitServerName: SIQAMJAN
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: SIQAJDBCAdapterTests
  version: "1.0"
  gitServerName: SIQAMJAN
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: DADA_GlobalVariable1
  version: "1.0"
  gitServerName: SIQAMJAN
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: WmJDBCAdapter
  version: 10.3.0.0.34
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
- name: WmSalesforceProvider
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
services:
- serviceName: project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_2
  packages:
  - name: SIQAMJAN30MayProject
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:getData
  packages:
  - name: SIQAMJAN30MayProject
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: project.siqamjan30may.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.connections:siqatestSSoap
  packages:
  - name: SIQAMJAN30MayProject
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: project.siqamjan30may.integrations:DBTest
  packages:
  - name: SIQAMJAN30MayProject
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: SIQAJDBCAdapterTests.adapterServices:getData
  packages:
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqamjan30may.integrations:createDBtest
  packages:
  - name: SIQAMJAN30MayProject
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: project.siqamjan30may.integrations:salesforceSoap
  packages:
  - name: SIQAMJAN30MayProject
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: project.siqamjan30may.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.operations.actions:createaccount
  packages:
  - name: SIQAMJAN30MayProject
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: SIQACloudStreamsTests
    version: "1.0"
configurationVariables:
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.cr.password
  : "{AES}PG5Tb6QEvoGlmMKcNsze4ljvytV8PRHvfmUQtTsgqcPI8Yi+ekze7ovAUGnGE+qU"
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.pr.httpContentCharSet
  : ISO-8859-1
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1MJANMysql.connectionManagerSettings.poolable
  : "false"
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.trustStore
  : ""
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.poolIncrementSize
  : "1"
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.startupRetryCount
  : "0"
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.pr.followServerRedirects
  : "true"
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.minimumPoolSize
  : "1"
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.cn.keepAliveInterval
  : "300000"
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.dbType
  : MySQL
  ? iscloudstreamsconnectorservice.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:createaccount.connectionAlias
  : project.siqamjan30may.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.connections:siqatestSSoap
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.pr.userAgent
  : Cloudstreams
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1MJANMysql.connectionSettings.password
  : "{AES}D6/2AGfsSWDOcWCLrORnEQ=="
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.rh.requestHeaderValues
  : "text/xml,login"
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.databaseName
  : MYSQL_DATABASE
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.cn.hostnameVerifier
  : org.apache.http.conn.ssl.DefaultHostnameVerifier
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1MJANMysql.connectionSettings.databaseName
  : MYSQL_DATABASE
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1MJANMysql.connectionSettings.keyStore
  : ""
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.rh.requestHeaderNames
  : "Content-Type,SOAPAction"
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.sessionExpiry
  : "14"
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.cr.authSchemeType
  : none
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.transactionType
  : NO_TRANSACTION
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.timeoutType
  : fixed
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.maximumPoolSize
  : "10"
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1MJANMysql.connectionSettings.driverType
  : mysqlMJAN
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.startupRetryCount
  : "0"
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.cn.readTimeout
  : "180000"
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.cn.socketStaleCheck
  : "true"
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.cn.tcpNoDelay
  : "false"
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.portNumber
  : "3306"
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.poolable
  : "false"
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1MJANMysql.connectionEnabled
  : "false"
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.cn.enableSNI
  : "true"
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.cn.connectTimeout
  : "180000"
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.user
  : root
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1MJANMysql.connectionSettings.otherProperties
  : loginTimeout=60;driverType=2;
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.driverType
  : MQ
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.pr.allowCircularRedirects
  : "true"
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1MJANMysql.connectionSettings.transactionType
  : NO_TRANSACTION
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.cn.sockBuffSize
  : "8192"
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.expireTimeout
  : "1000"
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.cr.username
  : cspro@softwareag.com
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.cn.providerUrl
  : https://login.salesforce.com/services/Soap/u/53.0
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.cn.retryCount
  : "3"
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.serverName
  : 9.46.196.248
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.cn.retryIfRequestSentOk
  : "true"
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.cn.socketLinger
  : "-1"
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.cn.reuseAddr
  : "false"
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.cr.preemptiveAuthEnabled
  : "false"
  ? iscloudstreamsconnectorservice.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:createaccount.virtualServiceName
  : WmCloudStreams.SoapVS
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1MJANMysql.connectionSettings.serverName
  : 9.46.196.248
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.blockTimeout
  : "1000"
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.poolIncrementSize
  : "1"
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.cn.idleTimeout
  : "-1"
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.pr.useExpectCont
  : "false"
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1MJANMysql.connectionSettings.dbType
  : MySQL
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.cn.validateAfterInactivity
  : "1000"
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1MJANMysql.connectionSettings.trustStore
  : ""
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.datasourceClass
  : com.mysql.cj.jdbc.MysqlDataSource
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.expireTimeout
  : "1000"
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.pr.useChunking
  : "false"
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.otherProperties
  : loginTimeout=60;driverType=thin;
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.startupBackoffSecs
  : "10"
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1MJANMysql.connectionSettings.networkProtocol
  : tcp
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.cn.enableCompression
  : "false"
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.pr.serverRedirectMax
  : "5"
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.keyStore
  : ""
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.heartBeatInterval
  : "0"
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.poolable
  : "true"
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.pr.protocolVersion
  : HTTP/1.1
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.networkProtocol
  : tcp
  ? cloudstreamsconnection.project..siqamjan30may..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:siqatestSSoap.connectionEnabled
  : "true"
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1MJANMysql.connectionSettings.datasourceClass
  : com.mysql.cj.jdbc.MysqlDataSource
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionEnabled
  : "false"
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionSettings.password
  : "{AES}D6/2AGfsSWDOcWCLrORnEQ=="
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1MJANMysql.connectionSettings.user
  : siqatest
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1MJANMysql.connectionSettings.portNumber
  : "3306"
  ? artConnection.SIQAMJAN30MayProject.project.siqamjan30may.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2.connectionManagerSettings.blockingTimeout
  : "1000"
